---
sidebar: sidebar 
permalink: ontap-security-hardening/data-replication-encryption.html 
keywords: tr-4569, ontap hardening guide, encrypted SnapMirror, SnapVault, FlexCache, pre-shared key, TLS 1.2, TLS 1.3, TLS 
summary: 使用数据复制加密对 SnapMirror、SnapVault、FlexCache 的复制流量进行 TLS 加密，并在 ONTAP 集群之间使用预共享密钥。 
---
= 数据复制加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要补充静态数据加密，您可以使用带有预共享密钥的 TLS 加密集群之间的 ONTAP 数据复制流量，适用于 SnapMirror、SnapVault 或 FlexCache。

在为灾难恢复、缓存或备份复制数据时、您必须在通过线缆从一个ONTAP 集群传输到另一个集群期间保护这些数据。这样可以防止在敏感数据传输过程中对其进行恶意中间人攻击。

从 ONTAP 9.6 开始，集群对等加密为 ONTAP 数据复制功能（例如 SnapMirror、SnapVault 和 FlexCache）提供 TLS 1.2 AES-256 GCM 加密支持。加密通过两个集群对等体之间的预共享密钥（PSK）进行设置。

从 ONTAP 9.15.1 开始，集群对等加密为 ONTAP 数据复制功能（例如 SnapMirror、SnapVault 和 FlexCache）提供 TLS 1.3 AES-256 GCM 加密支持。加密通过两个集群对等体之间的预共享密钥 (PSK) 进行设置。

使用 NSE、NVE 和 NAE 等技术来保护静态数据的客户也可以使用端到端的数据加密，方法是升级到 ONTAP 9.6 或更高版本以使用集群对等加密。

集群对等加密集群对等之间的所有数据。例如，在使用 SnapMirror 时，所有对等信息以及源和目标集群对等之间的所有 SnapMirror 关系都会被加密。无法在启用集群对等加密的集群对等之间发送明文数据。

从 ONTAP 9.6 开始，新的集群对等关系默认情况下启用加密。要对 ONTAP 9.6 之前创建的集群对等关系启用加密，必须将源集群和目标集群升级到 9.6。此外，必须使用  `cluster peer modify` 命令更改源和目标集群对等体才能使用集群对等加密。

您可以在 ONTAP 9.6 中将现有对等关系转换为使用集群对等加密，如以下示例所示：

[listing]
----
On the destination cluster peer:

cluster2::> cluster peer modify cluster1 -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk

When prompted enter a passphrase.

On the source cluster peer:

cluster1::> cluster peer modify cluster2 -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk

When prompted enter the same passphrase you created in the previous step.
----