---
settings:
  name: ONTAP Technical Reports
  search: ontap-technical-reports, ontap-apps-dbs, netapp-solutions-sap
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: ONTAP技术报告
    url: "/index.html"
  - title: 应用程序和数据库
    url: "/apps-dbs.html"
  - title: 业务连续性
    url: "/business-continuity.html"
  - title: 数据保护和灾难恢复
    url: "/data-protection-disaster-recovery.html"
  - title: FlexCache和FlexGroup卷
    url: "/nas-containers.html"
  - title: NAS
    url: "/nas.html"
  - title: 网络
    url: "/networking.html"
  - title: SAN
    url: "/san.html"
  - title: 安全性
    entries:
    - title: 概述
      url: "/security.html"
    - section: ransomware-solutions
    - section: zero-trust
    - section: abac
  - title: 加强安全性
    entries:
    - title: 概述
      url: "/security-hardening-guides.html"
    - section: ontap-security-hardening
  - title: SnapCenter
    url: "/snapcenter.html"
  - title: 分层
    url: "/tiering.html"
  - title: 虚拟化
    url: "/virtualization.html"
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
